language-file: 'language.yml'       # EN language
language-file-de: 'language_de.yml' # DE language

team-sign-line: # definition first sign line
  - '[Team-Sign]'
  - '[team-sign]'
  - '[Team Sign]'
  - '[team sign]'
  - '[Team_Sign]'
  - '[team_sign]'