name: TeamChest
version: 1.0.0
main: karasurou.teamchest.TeamChest
author: Rouven Tjalf Rosploch (KarasuRou)
description: This plugin can create teams, which lead can designate a chest, that every team-member can use.
api-version: 1.18
commands:
  teamchest:
    permission: teamchest.command
    usage: /tc
    aliases: [tc, tech]
permissions:
  teamchest.debug:
    description: This permission is only for debug informations and should only be given to admins!
    default: op
  teamchest.command:
    description: Basic command permission, for team creation and chest usage
    default: true