name: TeamChest
version: 0.9.0
main: karasurou.teamchest.TeamChest
author: Rouven Tjalf Rosploch (KarasuRou)
website: https://github.com/KarasuRou/TeamChest
description: This plugin can create teams, which leader can designate a chest, that every team-member can use.
api-version: 1.18
libraries:
  - org.json:json:20211205
commands:
  teamchest:
    description: Type "/teamchest", "/tc" or "/tech" for help.
    permission: teamchest.command
    usage: /tc
    aliases: [tc, tech]
permissions:
  teamchest.debug:
    description: This permission is only for debug informations and should only be given to admins!
    default: op
  teamchest.command:
    description: Basic command permission, for team creation and chest usage.
    default: true